version: '3.1'
services:
  prisma:
    image: prismagraphql/prisma:1.20
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: ${PRISMA_DB_USER}
            password: ${PRISMA_DB_PASSWORD}
            migrations: true
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PRISMA_DB_USER}
      POSTGRES_PASSWORD: ${PRISMA_DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: