version: '2.1'

services:
  server-service:
    container_name: server-service
    build: ./services/server/
    volumes:
      - './services/server:/usr/src/app'
      - './services/server/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
      - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
  
  web-service:
    container_name: web-service
    build: ./services/web/
    volumes:
      - './services/web:/opt/app'
      - '/opt/app/node_modules'
    ports:
      - '8080:8080' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      server-service:
        condition: service_started
    links:
      - server-service